import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import utilStyles from "../styles/utils.module.scss";
import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiJquery,
  SiTypescript,
  SiReact,
  SiFirebase,
  SiMaterialui,
  SiRedux,
  SiNextdotjs,
  SiMongodb,
  SiTailwindcss,
  SiBootstrap,
  SiExpress,
  SiGithub,
  SiGitlab,
  SiFigma,
  SiBitbucket,
  SiHeroku,
  SiSlack,
  SiTrello,
} from "react-icons/si";
import { FaSass, FaNodeJs } from "react-icons/fa";
import { MdKeyboardArrowDown } from "react-icons/md";
import { CgArrowLongDown } from "react-icons/cg";
import { GrLocation } from "react-icons/gr";
import projectsData from "../projectsData/projectsdata";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Miyabi Tanimichi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.heroSection}>
          <div className={styles.heroWrap}>
            <div
              className={`${utilStyles.gradientTextKit} ${utilStyles.gradientPinkBlue}`}
            >
              <h1 className={`${utilStyles.headingJumbo} ${styles.heroFName}`}>
                Miyabi
              </h1>
              <h1 className={`${utilStyles.headingJumbo} ${styles.heroLName}`}>
                Tanimichi
              </h1>
            </div>
            <div
              className={`${utilStyles.gradientTextKit} ${utilStyles.gradientGray} ${styles.jobPositionWrap}`}
            >
              <h3
                className={`${utilStyles.headingSecJumbo} ${styles.jobPosition}`}
              >
                Front End Developer
              </h3>
            </div>
          </div>
          <div className={styles.arrowWrap}>
            <span className={styles.arrow}></span>
          </div>
        </section>
        <section className={styles.aboutSection}>
          <div className={styles.aboutContainer}>
            <h3 className={`${styles.title} ${utilStyles.heading2Xl}`}>
              Hello, I'm Miyabi :)
            </h3>
            <div className={styles.imgDescriptionWrap}>
              <div className={styles.imgWrap}>
                <Image
                  priority
                  src="/images/miyabi.JPG"
                  className={styles.image}
                  height={300}
                  width={300}
                  alt="miyabi"
                />
                <div
                  className={`${styles.imgDecoration} ${utilStyles.gradientPinkBlue}`}
                ></div>
              </div>
              <div className={`${styles.descriptionWrap} ${utilStyles.textMd}`}>
                <div className={styles.locationWrap}>
                  <GrLocation />
                  <p className={styles.location}>Vancouver, Canada</p>
                </div>
                <p className={`${styles.description} `}>
                  I'm a front end developer who is curious, motivated and always
                  eager to learn new skills.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className={styles.workSection}>
          <div className={styles.workContainer}>
            <h3
              className={`${utilStyles.headingJumbo} ${utilStyles.gradientGray} ${utilStyles.gradientTextKit} ${styles.title}`}
            >
              Works
            </h3>
            {projectsData?.map((project) => (
              <div className={styles.projectWrap} key={project.id}>
                <p
                  className={`${utilStyles.headingSecJumbo} ${utilStyles.gradientPinkBlue} ${utilStyles.gradientTextKit} ${styles.workTitle}`}
                >
                  {project.projectName}
                </p>
                <div className={styles.projectDetails}>
                  <p className={utilStyles.heading2Xl}>
                    {project.shortDescription}
                  </p>
                  <div className={styles.techStackWrap}>
                    <div>Tech Stack {">>"} </div>
                    {project.teckStack.map((techstack) => (
                      <div className={styles.techStack} key={techstack}>
                        <span>{techstack}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>
        <section className={styles.contactSection}>
          <p className={utilStyles.headingLg}>
            Please Feel Free to Reach Out to Me!
          </p>
          <a
            href="https://mail.google.com/mail/u/0/?fs=1&tf=cm&source=mailto&su=Let%27s+talk&to=miyabitanimichi@gmail.com"
            className={`${utilStyles.heading3Xl} ${styles.emailLink} ${utilStyles.gradientGray} ${utilStyles.gradientTextKit}`}
            target="_blank"
            rel="noopener noreferrer"
          >
            miyabitanimichi@gmail.com
          </a>
        </section>
      </main>
    </div>
  );
};

export default Home;
