import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiJquery,
  SiTypescript,
  SiReact,
  SiFirebase,
  SiMaterialui,
  SiRedux,
  SiNextdotjs,
  SiMongodb,
  SiTailwindcss,
  SiBootstrap,
  SiExpress,
  SiGithub,
  SiGitlab,
  SiFigma,
  SiBitbucket,
  SiHeroku,
  SiSlack,
  SiTrello,
} from "react-icons/si";
import { FaSass, FaNodeJs } from "react-icons/fa";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Miyabi Tanimichi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          Hello, I am Miyabi Tanimichi, Front End Developer based in Vancouver
        </h1>
        <h3></h3>
        <p>Skills</p>
        <div>
          <SiHtml5 />
          <SiCss3 />
          <FaSass />
          <SiJavascript />
          <SiJquery />

          <SiTypescript />
          <SiReact />
          <SiRedux />
          <SiNextdotjs />
          <SiMaterialui />
          <SiTailwindcss />
          <SiBootstrap />
          <FaNodeJs />
          <SiExpress />
          <SiFirebase />
          <SiMongodb />
          <SiGithub />
          <SiGitlab />
          <SiBitbucket />
          <SiSlack />
          <SiTrello />
          <SiFigma />
          <SiHeroku />
        </div>

        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
