import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import utilStyles from "../styles/utils.module.scss";
import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiJquery,
  SiTypescript,
  SiReact,
  SiFirebase,
  SiMaterialui,
  SiRedux,
  SiNextdotjs,
  SiMongodb,
  SiTailwindcss,
  SiBootstrap,
  SiExpress,
  SiGithub,
  SiGitlab,
  SiFigma,
  SiBitbucket,
  SiHeroku,
  SiSlack,
  SiTrello,
} from "react-icons/si";
import { FaSass, FaNodeJs } from "react-icons/fa";
import { MdKeyboardArrowDown } from "react-icons/md";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Miyabi Tanimichi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.heroSection}>
          {/* <div className={styles.titlesWrap}>
            <h1 className={utilStyles.heading2Xl}>
              Hello, I am <span className={styles.name}>MIYABI TANIMICHI</span>
            </h1>
            <h2 className={utilStyles.headingXl}>
              A motivated, passionate and open-minded Front End Developer based
              in Vancouver
            </h2>
          </div>
          <div className={styles.skillsWrap}>
            <h3 className={utilStyles.headingLg}>Skills</h3>
            <div className={styles.skillsIcons}>
              <SiHtml5 />
              <SiCss3 />
              <FaSass />
              <SiJavascript />
              <SiJquery />
              <SiTypescript />
              <SiReact />
              <SiRedux />
              <SiNextdotjs />
              <SiMaterialui />
              <SiTailwindcss />
              <SiBootstrap />
              <FaNodeJs />
              <SiExpress />
              <SiFirebase />
              <SiMongodb />
              <SiGithub />
              <SiGitlab />
              <SiBitbucket />
              <SiSlack />
              <SiTrello />
              <SiFigma />
              <SiHeroku />
            </div>
          </div> */}
          <div className={styles.heroNames}>
            <h1 className={utilStyles.headingJumbo}>Miyabi</h1>
            <h1 className={utilStyles.headingJumbo}>Tanimichi</h1>
          </div>
          <div className={styles.heroJobPosition}>
            <h3 className={utilStyles.headingSecJumbo}>Front End Developer</h3>
          </div>
          <div className={styles.navigator}>
            <MdKeyboardArrowDown className={styles.arrow} />
          </div>
        </section>
        <section className={styles.aboutSection}>
          <div className={styles.aboutContainer}>
            <h3 className={`${styles.title} ${utilStyles.heading2Xl}`}>
              About Me
            </h3>
            <div className={styles.titlePicWrap}>
              <Image
                priority
                src="/images/miyabi.JPG"
                className={styles.image}
                height={300}
                width={300}
                alt="miyabi"
              />
              <p className={`${styles.description} ${utilStyles.text}`}>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis
                doloribus voluptates alias magni deserunt. Hic recusandae
                expedita quidem velit, debitis odit possimus eum temporibus
                adipisci omnis maxime ut modi quisquam. Lorem, ipsum dolor sit
                amet consectetur adipisicing elit. Nobis doloribus voluptates
                alias magni deserunt. Hic recusandae expedita quidem velit,
                debitis odit possimus eum temporibus adipisci omnis maxime ut
                modi quisquam. Lorem, ipsum dolor sit amet consectetur
                adipisicing elit. Nobis doloribus voluptates alias magni
                deserunt. Hic recusandae expedita quidem velit, debitis odit
                possimus eum temporibus adipisci omnis maxime ut modi quisquam.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nobis
                doloribus voluptates alias magni deserunt. Hic recusandae
                expedita quidem velit, debitis odit possimus eum temporibus
                adipisci omnis maxime ut modi quisquam. Lorem, ipsum dolor sit
                amet consectetur adipisicing elit. Nobis doloribus voluptates
                alias magni deserunt. Hic recusandae expedita quidem velit,
                debitis odit possimus eum temporibus adipisci omnis maxime ut
                modi quisquam. Lorem, ipsum dolor sit amet consectetur
                adipisicing elit. Nobis doloribus voluptates alias magni
                deserunt. Hic recusandae expedita quidem velit, debitis odit
                possimus eum temporibus adipisci omnis maxime ut modi quisquam.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
