import React from "react";
import Header from "./header/Header";
import Footer from "./footer/Footer";
import Head from "next/head";

const Layout: React.FC = ({ children }) => {
  return (
    <div className="content">
      <Head>
        <title>Miyabi Tanimichi</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="initial-scale=1.0, width=device-width"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
};

export default Layout;
